language: node_js
node_js:
  - 12
before_script:
  - npm install @11ty/eleventy -g
script: npm run build:css && npm run build:eleventy
deploy:
  local-dir: dist
  provider: pages
  skip-cleanup: true

  github-token: $GITHUB_TOKEN
  keep-history: true

  target_branch: gh-pages
  on:
    branch: master
